FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o go-backend-template ./cmd/api

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/go-backend-template ./go-backend-template

EXPOSE 3000

CMD ["./go-backend-template"]
