version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go-backend-template:
    image: go-backend-template:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: go-backend
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    env_file:
      .env
    depends_on:
      - postgres-db

volumes:
  pgdata:
